# Generated by Django 4.0.4 on 2022-05-31 12:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='surname',
        ),
        migrations.AddField(
            model_name='post',
            name='post_content',
            field=models.CharField(default='body', max_length=10000),
        ),
        migrations.AddField(
            model_name='post',
            name='post_title',
            field=models.CharField(default='heading', max_length=10000),
        ),
        migrations.AddField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
