# Generated by Django 4.0.4 on 2022-06-08 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_address_bio_doctor_people_product_delete_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='people_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='people',
            name='people_title',
            field=models.CharField(max_length=100),
        ),
    ]
