# Generated by Django 4.0.4 on 2022-06-08 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_people_people_name_alter_people_people_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='email',
            field=models.EmailField(default='ofoh@gmail.com', max_length=254),
        ),
    ]
