# Generated by Django 4.0.4 on 2022-06-08 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_bio_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_price',
            field=models.CharField(default=500, max_length=10),
        ),
    ]
